### PR TITLE
Revisions to Wiki

### PR DESCRIPTION
**Pull request by audreykoz**
Hey Herve!
I've gone through and completed my suggestions to improve the wiki. I ended up cloning your wiki as a submodule into my repo, so hopefully, you can pull my changes, but let me know if you have any issues/suggestions.

### CODE REVIEW

**Comment by audreykoz** [comment]
Also, I am planning on working on the wiki for the specialization plugin, I just haven't gotten to it yet:)

**Comment by herve91** [comment]
Thank you very much Audrey :-)

**Comment by audreykoz** [comment]
Hey, sorry to bother but I believe that in order to get my version of the wiki to show up on your wiki page, you need to clone and pull changes
There was a good thread on how to do this: https://gist.github.com/larrybotha/10650410

**Comment by herve91** [comment]
Hi Audrey,

My apologies for this late answer, but I was not available this weekend. I'll have a look to your procedure.

Thanks again
Hervé

**Comment by herve91** [comment]
Done ...

Not using the procedure you provided because I did not understand it at all, but done anyway :-)

Thanks again Audrey :-)

**Comment by audreykoz** [comment]
Looks good!

**Pull request merged**
